name: Build Executables

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

env:
  VERSION: ${{ github.ref_name }} # e.g. v1.1.1 or 1.1.1

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Windows Executable
        run: dotnet publish -c Release -r win-x64 --self-contained true `
               /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true `
               -o ./X4PlayerShipTradeAnalyzer
        shell: pwsh

      - name: Prepare Windows package
        run: |
          $ver = "${{ env.VERSION }}".TrimStart("v")
          cp README.md X4PlayerShipTradeAnalyzer
          if (Test-Path ./X4PlayerShipTradeAnalyzer/X4PlayerShipTradeAnalyzer.pdb) {
            rm ./X4PlayerShipTradeAnalyzer/X4PlayerShipTradeAnalyzer.pdb
          }
          7z a -tzip X4PlayerShipTradeAnalyzer_$ver.zip X4PlayerShipTradeAnalyzer
        shell: pwsh

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-zip
          path: X4PlayerShipTradeAnalyzer_${{ env.VERSION }}.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Linux Executable
        run: dotnet publish ./X4PlayerShipTradeAnalyzer.csproj -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true -o ./X4PlayerShipTradeAnalyzer


      - name: Make executable
        run: chmod +x ./X4PlayerShipTradeAnalyzer/X4PlayerShipTradeAnalyzer

      - name: Prepare Linux package
        run: |
          ver="${VERSION#v}"
          cp README.md X4PlayerShipTradeAnalyzer
          rm -f ./X4PlayerShipTradeAnalyzer/X4PlayerShipTradeAnalyzer.pdb || true
          tar -czf X4PlayerShipTradeAnalyzer_${ver}.tar.gz X4PlayerShipTradeAnalyzer

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-tar
          path: X4PlayerShipTradeAnalyzer_${{ env.VERSION }}.tar.gz

  release-and-scan:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    if: ${{ github.event_name == 'release' }}
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: win-zip

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-tar

      - name: Attach archives to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            X4PlayerShipTradeAnalyzer_${{ env.VERSION }}.zip
            X4PlayerShipTradeAnalyzer_${{ env.VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      - name: VirusTotal scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          update_release_body: true
          request_rate: 4
          vt_api_key: ${{ secrets.VT_API_KEY }}
          github_token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          files: |
            X4PlayerShipTradeAnalyzer_${{ env.VERSION }}.zip
            X4PlayerShipTradeAnalyzer_${{ env.VERSION }}.tar.gz